### ISSUE TITLE
LICENSE compatibility with upstream

### ISSUE THREAD

**Issue by skeggse** [antimatter15/bzip2.js#3]
It looks like bzip2.js is based on [micro-bunzip](http://landley.net/code/) by Rob Landley, which is licensed under the LGPLv2. You've updated the license on bzip2.js to the MIT license, but given that your code appears to be a derivative of micro-bunzip, I think that means you need to license bzip2.js under the LGPL or the GPL (unless you have permission from Rob Landley to do otherwise).

**Comment by cscott** [comment]
Rob Landley has updated his code to "zero-clause BSD" (see https://github.com/yeoman/generator/issues/830#issuecomment-124228842).  So I think @antimatter15's MIT license is now retroactively okay?

**Comment by antimatter15** [comment]
woo
